baseURL = "http://qwq.cool/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "独角兽的梦"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 6                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true
publishDir = "docs"

[author]                               # essential                     # 必需
  name = "独角兽"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "千古是非心，一夕渔樵话。"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "送你这棵花 来怀念已逝初夏"                                   # site's footer slogan  # 网站页脚标语
  keywords = ["Hugo","theme","zozo"]                                  # site's keywords  # 网站关键字
  description = "独角兽的梦"                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = true
  appId = "9FQQvuxgYbIG6OhOA3Tw9AFx-gzGzoHsz"
  appKey = "kgHz9QodYppGh7xiztDUVhYk"
  placeholder = " "
  visitor = true

# Your socail's url
[social]
  twitter = "https://twitter.com/transferingz"
  weibo = "https://www.weibo.com/u/1749041570"
  telegram = "https://telegram.me/lixuyang"
  zhihu = "https://www.zhihu.com/people/lee-xuyang"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true